_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_val_100",)
  TEST: ("coco_2017_val_100",)
SOLVER:
  BASE_LR: 0.001
  STEPS: (30,)
  MAX_ITER: 40
  IMS_PER_BATCH: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
    CLIP_VALUE: 1.0
    NORM_TYPE: .inf
DATALOADER:
  NUM_WORKERS: 2
